// Code generated by ent, DO NOT EDIT.

package transaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the transaction type in the database.
	Label = "transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeFromWallet holds the string denoting the from_wallet edge name in mutations.
	EdgeFromWallet = "from_wallet"
	// EdgeToWallet holds the string denoting the to_wallet edge name in mutations.
	EdgeToWallet = "to_wallet"
	// Table holds the table name of the transaction in the database.
	Table = "transactions"
	// FromWalletTable is the table that holds the from_wallet relation/edge.
	FromWalletTable = "transactions"
	// FromWalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	FromWalletInverseTable = "wallets"
	// FromWalletColumn is the table column denoting the from_wallet relation/edge.
	FromWalletColumn = "wallet_sent_transactions"
	// ToWalletTable is the table that holds the to_wallet relation/edge.
	ToWalletTable = "transactions"
	// ToWalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	ToWalletInverseTable = "wallets"
	// ToWalletColumn is the table column denoting the to_wallet relation/edge.
	ToWalletColumn = "wallet_recieved_transactions"
)

// Columns holds all SQL columns for transaction fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transactions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"wallet_sent_transactions",
	"wallet_recieved_transactions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(uint) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Transaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByFromWalletField orders the results by from_wallet field.
func ByFromWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFromWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByToWalletField orders the results by to_wallet field.
func ByToWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newToWalletStep(), sql.OrderByField(field, opts...))
	}
}
func newFromWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FromWalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FromWalletTable, FromWalletColumn),
	)
}
func newToWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ToWalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ToWalletTable, ToWalletColumn),
	)
}
