services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - DATABASE_URL=postgresql://test_user:test_password@database:5432/test_db?sslmode=disable
    ports:
      - "8080:8080"
    command: >
      sh -c "/app/migrate && /app/app"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    
volumes:
  db_data: