// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"test_infotex/ent/transaction"
	"test_infotex/ent/wallet"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int `json:"amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// FromWalletID holds the value of the "from_wallet_id" field.
	FromWalletID int `json:"from_wallet_id,omitempty"`
	// ToWalletID holds the value of the "to_wallet_id" field.
	ToWalletID int `json:"to_wallet_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransactionQuery when eager-loading is set.
	Edges        TransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TransactionEdges holds the relations/edges for other nodes in the graph.
type TransactionEdges struct {
	// FromWallet holds the value of the from_wallet edge.
	FromWallet *Wallet `json:"from_wallet,omitempty"`
	// ToWallet holds the value of the to_wallet edge.
	ToWallet *Wallet `json:"to_wallet,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FromWalletOrErr returns the FromWallet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) FromWalletOrErr() (*Wallet, error) {
	if e.FromWallet != nil {
		return e.FromWallet, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: wallet.Label}
	}
	return nil, &NotLoadedError{edge: "from_wallet"}
}

// ToWalletOrErr returns the ToWallet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) ToWalletOrErr() (*Wallet, error) {
	if e.ToWallet != nil {
		return e.ToWallet, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: wallet.Label}
	}
	return nil, &NotLoadedError{edge: "to_wallet"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID, transaction.FieldAmount, transaction.FieldFromWalletID, transaction.FieldToWalletID:
			values[i] = new(sql.NullInt64)
		case transaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (t *Transaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case transaction.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				t.Amount = int(value.Int64)
			}
		case transaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case transaction.FieldFromWalletID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_wallet_id", values[i])
			} else if value.Valid {
				t.FromWalletID = int(value.Int64)
			}
		case transaction.FieldToWalletID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_wallet_id", values[i])
			} else if value.Valid {
				t.ToWalletID = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transaction.
// This includes values selected through modifiers, order, etc.
func (t *Transaction) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryFromWallet queries the "from_wallet" edge of the Transaction entity.
func (t *Transaction) QueryFromWallet() *WalletQuery {
	return NewTransactionClient(t.config).QueryFromWallet(t)
}

// QueryToWallet queries the "to_wallet" edge of the Transaction entity.
func (t *Transaction) QueryToWallet() *WalletQuery {
	return NewTransactionClient(t.config).QueryToWallet(t)
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Transaction) Update() *TransactionUpdateOne {
	return NewTransactionClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Transaction) Unwrap() *Transaction {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Transaction is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", t.Amount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("from_wallet_id=")
	builder.WriteString(fmt.Sprintf("%v", t.FromWalletID))
	builder.WriteString(", ")
	builder.WriteString("to_wallet_id=")
	builder.WriteString(fmt.Sprintf("%v", t.ToWalletID))
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction
